[tool.poetry]
name = "gehenna-api"
version = "0.1.0"
description = "API Rest para gerenciamento de coleções e decks de V:TES"
authors = ["Claudio Torcato <claudiotorcato@gmail.com>"]
readme = "README.md"
packages = [{include = "gehenna_api"}]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.100.1"
uvicorn = "^0.23.2"


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
pytest-doc = "^0.0.1"
taskipy = "^1.12.0"
blue = "^0.9.1"
ruff = "^0.0.282"
httpx = "^0.24.1"
isort = "^5.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
