"""coluna code em moviments

Revision ID: 2ac76c6d1bc4
Revises: ae6e29eb2a7f
Create Date: 2023-09-09 16:14:01.059582

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2ac76c6d1bc4'
down_revision: Union[str, None] = 'ae6e29eb2a7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moviments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moviments', schema=None) as batch_op:
        batch_op.drop_column('code')

    # ### end Alembic commands ###
