"""create moviments table

Revision ID: 78437d4c7122
Revises: f4133bab9541
Create Date: 2023-09-01 16:13:52.957228

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '78437d4c7122'
down_revision: Union[str, None] = 'f4133bab9541'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moviments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('date_move', sa.Date(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
#    op.alter_column('cards', 'tipo',
#               existing_type=sa.VARCHAR(),
#               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
#    op.alter_column('cards', 'tipo',
#               existing_type=sa.VARCHAR(),
#               nullable=True)
    op.drop_table('moviments')
    # ### end Alembic commands ###
