"""column owner em moviments

Revision ID: ae6e29eb2a7f
Revises: 78437d4c7122
Create Date: 2023-09-02 16:00:46.512656

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ae6e29eb2a7f'
down_revision: Union[str, None] = '78437d4c7122'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('moviments', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_moviments_users_id_users', 'users', ['owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moviments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_moviments_users_id_users', type_='foreignkey')

    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
