"""updated null

Revision ID: cf089a457a4a
Revises: b93635a06706
Create Date: 2023-10-20 21:05:44.228194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf089a457a4a'
down_revision: Union[str, None] = 'b93635a06706'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decks', schema=None) as batch_op:
        batch_op.alter_column('updated',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decks', schema=None) as batch_op:
        batch_op.alter_column('updated',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
